require 'fileutils'
require 'rubygems'

# Some utility functions
def set(key, value)
  if false == value
    value = 'FALSE'
  elsif true == value
    value = 'TRUE'
  end
  ENV[key.to_s.upcase] = value
end

def fetch(key)
  val = ENV[key.to_s.upcase]
  if 'FALSE' == val
    val = false
  elsif 'TRUE' == val
    val = true
  end
  val
end

# Hardcoding these paths here - adjust them as necessary. These shouldn't change much (if at all)
@mono = '/Library/Frameworks/Mono.framework/Versions/Current/bin/mono'
@mdtool = '/Applications/Xamarin\\ Studio.app/Contents/MacOS/mdtool build'
@xbuild = '/usr/bin/xbuild'
@test_cloud = "#{@mono} ./packages/Xamarin.UITest.0.6.8/tools/test-cloud.exe"
@xamarin_component = "#{@mono} --runtime=v4.0 ./xamarin-component.exe"

@test_assembly_dir = "./CreditCardValidation.UITests/bin/Debug/"
@apk = './CreditCardValidation.Droid/bin/Debug/CreditCardValidation.Droid.apk'
@ipa = './CreditCardValidation.iOS/bin/iPhone/Debug/CreditCardValidationiOS-1.0.ipa'
@dsym = './CreditCardValiation.iOS/bin/iPhone/Debug/CreditCardValidationiOS.app.dSYM'

# These values will come from either the file rake_env or environment variables
@testcloud_api_key = fetch(:xtc_api_key)
@android_device_id = fetch(:android_device_id)
@ios_device_id = fetch(:ios_device_id)

task :default => [:clean, :build]

task :require_environment do
  if @testcloud_api_key.nil? || 0 == @testcloud_api_key.length
    raise Exception.new("No Test Cloud API key specified - set the XTC_API_KEY environment variable.")
  end

  if @android_device_id.nil? || 0 == @android_device_id.length
    raise Exception.new("No Android Device ID specified - set the ANDROID_DEVICE_ID environment variable.")
  end

  if @ios_device_id.nil? || 0 == @ios_device_id.length
    raise Exception.new("No iOS Device ID specified - set the IOS_DEVICE_ID environment variable.")
  end

end

desc "Cleans the project, removing any artifacts from previous builds"
task :clean do
  directories_to_delete = [
      "./screenshots",
      "./test_servers",
      "./testresults.html",
      "./CreditCardValidation.iOS/bin",
      "./CreditCardValidation.iOS/obj",
      "./CreditCardValidation.Droid/bin",
      "./CreditCardValidation.Droid/obj",
      "./CreditCardValidation.Core/bin",
      "./CreditCardValidation.Core/obj"
  ]

  directories_to_delete.each { |x|
    rm_rf x
  }
end

desc "Compiles the Android and iOS projects."
task :build => [:clean, :build_android, :build_ios] do

end

task :build_android do
  system("#{@xbuild} /verbosity:diagnostic /t:Package /p:Configuration=Release /p:AndroidUseSharedRuntime=false /p:EmbedAssembliesIntoApk=true ./CreditCardValidation.Droid/CreditCardValidation.Droid.csproj")
  system("#{@xbuild} /verbosity:diagnostic /t:Package /p:Configuration=Debug /p:AndroidUseSharedRuntime=false /p:EmbedAssembliesIntoApk=true ./CreditCardValidation.Droid/CreditCardValidation.Droid.csproj")

end

task :build_ios do
  puts "Build the IPA:"
  system("#{@mdtool} \"--configuration:Debug|iPhone\" CreditCardValidation.sln")
  system("#{@mdtool} \"--configuration:Release|iPhone\" CreditCardValidation.sln")

  puts "Build the iPhoneSimulator:"
  system("#{@mdtool} build \"--configuration:Debug|iPhoneSimulator\" CreditCardValidation.sln")
end

desc "Builds the application and then submits the APK and IPA to Xamarin Test Cloud."
task :xtc => [:xtc_android, :xtc_ios] do

end

task :xtc_android => [:require_environment] do
  raise "Missing the APK #{@apk}." unless File.exists?(@apk)
  command_line = "#{@test_cloud} submit #{@apk} #{@testcloud_api_key} --devices #{@android_device_id} --assembly-dir #{@test_assembly_dir} --app-name \"Simple Credit Card Validator\""
  tests_passed = system(command_line)
  raise "Some tests failed in test cloud - check the build log. #{command_line}" unless tests_passed
end

task :xtc_ios => [:require_environment] do
  raise "Missing the IPA #{@ipa}." unless File.exists?(@ipa)
  command_line = "#{@test_cloud} submit #{@ipa} #{@testcloud_api_key} --devices #{@ios_device_id} --assembly-dir #{@test_assembly_dir} --app-name \"Simple Credit Card Validator\" --dsym $DSYM"
  tests_passed = system(command_line)
  raise "Some tests failed in test cloud - check the build log." unless tests_passed
end

task :install_components do
  system("#{@xamarin_component} restore CreditCardValidation.sln")
end